SYS-3208 - Adds Maven build workflow
bestseller-ecom/bestseller-pipelines pull request #22
Opened 2022-09-20 15:52 UTC by hugolesta

This commit aims to add Maven build
workflow, to be able to build JAVA
projects that are using Maven

2022-09-20 16:35 UTC, mattialacroce commented
General consideration:
In teamcity we built an image to use it in the deploy, and we created an ECR, probably never cleaned up.
If i am not mistaken here, we just need some artifacts as output of a build, we don't necessarily need the ECR image. Am i wrong? or we can think about improve this process without pushing/pulling a new ECR each time?

2022-09-21 07:48 UTC, hugolesta commented
I’ll explain how the app work in this case. My notes below:

This project is a JAVA project, which means we have to build it using the pom.xml  file, after building the app, several artifacts will be stored in the target directory, those artifacts seem to be ephemeral.

Those artifacts will be used for docker to run /app.jar, so they are dependent on each other.

When the build happens, we’ll have a docker image, and it will have the tag that is the pre-build SHA (previous step), we’ll push that image to ECR.

Deploy: When we deploy the app (I have to test it), we gonna get the task definition as a JSON, and then, replace the image that we already have here, with the previous image we already pushed (GitHub SHA), and then deploy it.

So, we have the images versioned using the GitHub SHA, which is compatible with future works (rollback)

I’m working on the translate of the pipeline from TeamCity to GitHub, for sure we can enhance this work (refactor)

2022-09-21 08:18 UTC, mattialacroce approved these changes

2022-09-21 08:22 UTC, hugolesta commented on .github/workflows/build-maven.yml
> +        default: "temurin"
I chose that one because it’s high performant, cross-platform, open-source licensed, and Java SE TCK-tested for general use across the Java ecosystem.

Do you have information about the distributions we are using at BSE? Would be nice to have feedback and chose the one that fit better the BSE needs. [](edited-with-Axolo)

2022-09-21 08:27 UTC, mattialacroce commented on .github/workflows/build-maven.yml
> +        default: "temurin"
No i don't have infos but we can check, for now it is good i would say :slightly_smiling_face: [](edited-with-Axolo)

2022-09-21 08:55 UTC, felipem1210 commented
I suggest changing the name of the file to: docker-build-java.yml

2022-09-21 09:12 UTC, felipem1210 commented
better: build-docker-java.yml

2022-09-21 09:19 UTC, hugolesta commented
We were talking with the guys in the daily, and it seems different ways to build in JAVA can even exist in the company, so I’ll suggest changing the name maybe to

build-docker-maven.yml

ok, keep it as it’s.

Please, @felipem1210, @mattialacroce, @guilhermewolf, abdulgafaar.abioye, @agurebora  feel free to provide your opinion about this.

2022-09-21 09:20 UTC, mattialacroce commented
agreed, javier's team uses gradle, not maven, so we need to be more specific here :slightly_smiling_face:

2022-09-21 09:28 UTC, felipem1210 commented
The process for building java lambda will be slightly different. And it will be also with maven

2022-09-21 09:28 UTC, felipem1210 commented
let’s discuss it tomorrow

2022-09-21 09:30 UTC, agurebora commented
inputs from dev teams would be valuable here

2022-09-21 09:31 UTC, hugolesta commented
I’ll contact with Javier to talk a bit, probably tomorrow he will work in the office.

2022-09-22 13:37 UTC, mattialacroce approved these changes

2022-09-23 07:49 UTC, guilhermewolf submitted a review, later dismissed

2022-09-23 07:53 UTC, felipem1210 commented
Are you going to change the name of the file?

2022-09-23 07:54 UTC, felipem1210 requested changes
Change the name of the file

2022-09-23 09:36 UTC, hugolesta commented
Yes I’m going to,  omw to change the logic. I’ll keep you posted here.

2022-09-23 13:02 UTC, felipem1210 approved these changes

2022-09-23 13:12 UTC, guilhermewolf approved these changes

2022-09-23 13:24 UTC, merged