SYS-3237 - Adds new Worflow documentation
bestseller-ecom/bestseller-pipelines pull request #28
Opened 2022-09-28 13:58 UTC by hugolesta

This commit aims to add new Worflow documentation
for every workflow we have in the bestseller-pipeline repository.

2022-09-28 14:22 UTC, felipem1210 requested changes

2022-09-28 14:22 UTC, felipem1210 commented on docs/build-java-lambda.md
> +| build-tool | The build type `['maven', 'gladle']`. Maven by default | `false` | `maven` |
is gradle, no gladle

2022-09-28 14:22 UTC, felipem1210 commented on docs/build.md
> +This workflow will provide a complete solution to build containers for Elastic Container Service.
I would say "a complete solution to build docker images"

2022-09-28 14:22 UTC, felipem1210 commented on docs/deploy-ecs.md
> +| scheduled-ecs-task | Enable/disable schedul task deployment | `false` | `false` |
Enable/disable scheduled task deployment

2022-09-28 14:27 UTC, mattialacroce commented
I think documenting each workflow does not add that much value with respect to the time spent. Developer will just copy paste or ask for examples eventually

2022-09-28 14:32 UTC, mattialacroce submitted a review, later dismissed

2022-09-29 09:31 UTC, felipem1210 approved these changes

2022-09-30 07:16 UTC, guilhermewolf approved these changes

2022-09-30 07:17 UTC, merged