SYS-3296 - fix: A documentation on dependabot and codeowners.
bestseller-ecom/bestseller-pipelines pull request #36
Opened 2022-10-17 14:20 UTC by Abdulgafaar

This PR is to add documentation on the usage of CODEOWNERS and dependabot.

2022-10-17 14:37 UTC, hugolesta requested changes

2022-10-17 14:37 UTC, hugolesta commented on docs/workflows/dependabot.md
> +This ensures that all dependencies are kept up to date and there are no vulnerabilities. it checks for the depencency files if there are outdated requierements and opens individual PRs if it finds an
Typo: should be "dependency" and "requirements"

2022-10-17 14:37 UTC, hugolesta commented on docs/workflows/codeowners.md
> +This is besically a file in the root directory of the repo to define teams that are responsible for the repository.
typo: basically

2022-10-18 07:59 UTC, Abdulgafaar commented
I have updated the doc based on your reviews.

2022-10-18 08:59 UTC, mattialacroce commented on docs/dependabot.md
> +This ensures that all dependencies are kept up to date and there are no vulnerabilities. it checks for the dependency files if there are outdated requirements and opens individual PRs if it finds any
"There are no vulnerabilities" is not exactly true ahhahah but it's okay!

2022-10-18 09:00 UTC, mattialacroce approved these changes

2022-10-19 08:15 UTC, hugolesta approved these changes

2022-10-19 08:45 UTC, merged